<?php
    include_once "header.php";
    require "refBootstrap.php";
?>
    <div class="main">
        <h2 class="subtitulo">Ultimas noticias: </h2><hr>
        <div class="section1">
            <p class="ultimasNoticias">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fuga quo repellat perferendis quisquam quos cupiditate? Nam, vitae quod nisi ea necessitatibus consectetur maiores! Minima debitis maxime dignissimos mollitia explicabo nobis eveniet voluptatibus commodi, rem iusto tempore sequi fugiat at. Necessitatibus iste nihil quidem eius, minima, pariatur ipsa inventore quae qui voluptatem molestias quas praesentium possimus molestiae, consequuntur provident. A asperiores ullam ipsam quo quibusdam numquam est illum amet, dolorem voluptas aperiam sit mollitia excepturi tenetur nihil. Quam vel incidunt obcaecati quia quasi officiis ad ducimus saepe tempora in itaque totam quo quibusdam officia odio fuga excepturi exercitationem, dolor enim commodi voluptatem, dolore placeat at consectetur. Eaque et quos debitis, neque, in ratione rerum, animi corrupti dignissimos dolores fugiat quibusdam. Mollitia ex deleniti reprehenderit provident itaque asperiores numquam. Quos vitae beatae eaque in tempora, nostrum neque ullam cumque exercitationem necessitatibus saepe, dolorem perferendis suscipit. Reprehenderit sequi assumenda esse labore accusamus porro placeat hic dolorem veniam pariatur perspiciatis nesciunt odit corrupti illo asperiores sapiente rem qui commodi autem officia vitae ipsam repellendus, eligendi dicta? Voluptatum consequatur est distinctio labore perferendis quos molestiae quia sit quisquam dolorem vero fuga nihil, explicabo, adipisci ea aliquam eos cumque temporibus quod tempora. Labore, temporibus nemo?</p>
            <a href="http://google.com">Para más información</a><br>
        </div>
        <div class="section2">
            <h2 class="subtitulo2">Además: </h2><hr>
            <p class="ademas">Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque enim rerum odio iusto animi itaque non cum quas repudiandae vero fugit nulla maxime incidunt reprehenderit ipsam aliquam inventore, sed ab, hic a, saepe consequatur! Doloribus et dolore cumque qui, ipsum tempora doloremque ex quaerat rem? Dolorum quis expedita eligendi esse sed facilis nam magni obcaecati perferendis quam corrupti, consequuntur itaque blanditiis ipsa minus nihil aut ipsam iusto voluptates harum adipisci dolore. Quas, officia quam in sed esse ex eum inventore fuga at maxime blanditiis, nostrum nulla voluptatum, temporibus minima officiis corporis laudantium aperiam praesentium similique incidunt nobis nesciunt veniam? Blanditiis repudiandae inventore aperiam! Dolore suscipit facere cumque corrupti esse eligendi mollitia beatae nesciunt neque id, excepturi, autem molestiae fugiat nobis, fugit doloribus iusto minima quisquam eveniet eos harum. Corrupti a nam ullam itaque mollitia, laborum adipisci quas voluptatem nobis, dolorum iusto totam sunt! Alias consequatur ad tempora sit debitis maxime fugit qui voluptatum voluptatibus veritatis vitae, ducimus cupiditate odit eos nisi quae ea expedita natus. Dolorem fuga vel nemo. Repellat eveniet in reiciendis commodi qui, tempore ipsum deleniti quod laudantium eum omnis culpa vitae illo pariatur aperiam minus porro eius expedita sed error rem id dicta quidem. Fugit, at hic?</p>
        </div>
        <div class="section3">
            <h2 class="subtitulo3">Sistema de turnos:</h2><hr>
            <p class="turnos">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa nihil dignissimos nulla earum, vero, itaque sequi inventore distinctio hic voluptatem soluta quam accusantium impedit? Quis explicabo numquam sapiente quisquam amet tempora illo vel a cupiditate quas unde optio nulla, earum iste fuga dolorum laudantium delectus officiis rerum velit pariatur perferendis. Qui magni beatae sed impedit laboriosam sint veritatis quae temporibus soluta delectus nisi est ut aperiam placeat facilis rem quibusdam perspiciatis suscipit debitis eos, dolorem libero. Harum nam quasi ullam, quisquam dolor rem enim, sequi minus aliquam modi nobis ab perferendis nulla. Voluptas temporibus rem minus id, fuga explicabo sunt.</p>
        </div>
        <div class="section4">
            <h2 class="subtitulo4">Cuidados:</h2><hr>
            <p class="cuidados">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur modi reprehenderit laborum suscipit maxime impedit, non inventore doloremque, ut ullam nobis soluta quisquam sint voluptatem hic eius, eligendi voluptas aliquid! Commodi quo aspernatur totam soluta tempora! Voluptatum, esse? Laboriosam et dolore cupiditate totam consequatur, blanditiis dolor numquam soluta perspiciatis possimus quos ab aspernatur rerum? Beatae molestiae dicta explicabo, obcaecati labore distinctio sapiente unde repellendus iure aliquid adipisci quam accusamus facilis? Perferendis quidem beatae vitae praesentium adipisci neque eius totam nemo unde magni possimus, similique quos illum odio esse quisquam aut.</p>
        </div>
        <div class="section5">
            <h2 class="subtitulo5">Nuestras sucursales: </h2><hr>
            <p class="sucursales">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ratione nihil, est atque exercitationem asperiores facilis numquam quod non culpa sint nemo repudiandae dolore modi! Cupiditate reprehenderit nam saepe tenetur. Neque earum animi et. Officia ab veritatis quisquam explicabo voluptas corporis quas. Hic laudantium natus quo eligendi eius deleniti in illum maxime voluptates accusantium sint earum, ratione error molestiae asperiores porro sapiente, atque totam aliquam laborum iste unde aliquid repellendus nemo? Eaque harum exercitationem assumenda reiciendis quidem. Repellat officiis a placeat consequuntur architecto quasi minus maiores earum ipsam est ipsa, tenetur commodi quae error reprehenderit qui dolor quo iure magni.</p>
        </div>
        <div class="section6">
            <h2 class="subtitulo6">Prestamos: </h2><hr>
            <p class="prestamos">Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis iste, odio omnis numquam magni corrupti placeat minus nam delectus est quo necessitatibus minima, officia nesciunt amet cum velit quae ducimus. Repellendus et tempora autem earum eaque eum, ipsam quos magni vel placeat cupiditate maiores exercitationem illum pariatur, esse consectetur iusto itaque officiis dolores est ullam provident. Quia, repellat tempore voluptas voluptatem adipisci sint nostrum et! Illum enim sit laborum quibusdam mollitia assumenda ab excepturi, vero quo maxime ipsum illo? Adipisci non itaque rerum unde molestiae laborum ad sapiente voluptatem ab, quia id sequi accusantium quibusdam perferendis aperiam voluptate veritatis commodi dignissimos expedita odit doloribus fuga aut. Labore suscipit rem obcaecati ex possimus facilis cumque quo nam veritatis rerum commodi asperiores nihil sed facere necessitatibus, nisi maxime hic architecto doloremque nostrum culpa quas. Autem ducimus aspernatur totam doloribus, dolorum libero. Consequatur eos sunt dolor vitae laboriosam id illum similique aliquam incidunt rerum at, commodi quidem doloribus cum quia tempore blanditiis delectus laborum. Non soluta illum vel incidunt ex asperiores unde, harum, vitae recusandae et commodi in sunt tenetur voluptas a officia. Natus magni, cum repudiandae pariatur sit eligendi asperiores rerum provident laudantium, distinctio minima odit consequatur? Praesentium, commodi consectetur magnam eos amet distinctio ipsam, aspernatur similique culpa, dolor nihil quae adipisci possimus odit. Animi itaque laborum, aspernatur delectus doloribus dolores nemo quidem numquam quas, modi debitis! Eum rerum labore velit doloremque excepturi quae fugit quasi possimus fugiat? Porro rem sed voluptas itaque nemo doloribus harum omnis exercitationem necessitatibus expedita quas similique fugit suscipit ad repudiandae sapiente cumque consequuntur delectus voluptatum, atque, molestiae ullam nostrum ducimus. Maiores non dicta neque dolores repudiandae beatae est earum sapiente, alias iste odit soluta. Ab fugit veritatis neque officiis quod laudantium id eligendi a totam, perferendis, reiciendis nulla impedit dolorem numquam blanditiis illo exercitationem esse quidem.</p>
        </div>
        <div class="section7">
            <h2 class="subtitulo6">Creditos: </h2><hr>
            <p class="creditos">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo aut magnam nam accusantium vitae, ullam molestiae cupiditate eos eius assumenda et laudantium nisi distinctio praesentium nesciunt officiis quam, blanditiis numquam iure dolor commodi officia? Veniam laboriosam hic voluptate ea eaque repellat deleniti a harum labore vel pariatur facere ipsa, quia odio quo quis? Debitis, cumque optio! Maiores nobis, quam possimus nam inventore dicta unde voluptatem ratione sapiente commodi blanditiis vel nemo? Velit laborum rerum ipsum corrupti eius error dignissimos in officia fuga? Praesentium nostrum ex magnam, voluptatibus placeat consequatur, eos aliquam reprehenderit id ab vero minus adipisci ad beatae iusto?</p>
        </div>
    </div>

<?php
    include_once "footer.php";
?>